### ISSUE TITLE
Util.swift:12:8: No such module 'CommonCrypto'

### ISSUE THREAD

**Issue by danielfeelfine** [kryptco/swift-pgp#3]
How are you solving this?

**Comment by agrinman** [comment]
Go to Build Phases and add this `run script` phase:

```bash
modulesDirectory=$DERIVED_FILES_DIR/modules
modulesMap=$modulesDirectory/module.modulemap
modulesMapTemp=$modulesDirectory/module.modulemap.tmp

mkdir -p "$modulesDirectory"

cat > "$modulesMapTemp" << MAP
module CommonCrypto [system] {
    header "$SDKROOT/usr/include/CommonCrypto/CommonCrypto.h"
    export *
}
MAP

diff "$modulesMapTemp" "$modulesMap" >/dev/null 2>/dev/null
if [[ $? != 0 ]] ; then
mv "$modulesMapTemp" "$modulesMap"
else
rm "$modulesMapTemp"
fi
```

<img width="959" alt="screen shot 2017-08-31 at 11 55 25 am" src="https://user-images.githubusercontent.com/356333/29932834-722f707e-8e43-11e7-848e-49b9eb3cc8e6.png">

**Comment by danielfeelfine** [comment]
I try with this, but it's not work, the same problem.

*Another question*: is it possible to make a [React Native](https://facebook.github.io/react-native/) module with the [swift-pgp](https://github.com/kryptco/swift-pgp)? With this module is possible to generate new PGP keys?

Thanks

**Comment by agrinman** [comment]
Could you give some more context on what you're doing please?
I am not too familiar with react but there's no reason I can think of why it wouldn't work please.

**Comment by agrinman** [comment]
Closing for now. Please re-open if anything changes.
