### ISSUE TITLE
Use of unresolved identifier in swift 4.2 crc_octets

### ISSUE THREAD

**Issue by SPrabhudesai** [kryptco/swift-pgp#6]
Hi 

     I try using kryptoco in iOS swift but it showing error "Use of unresolved identifier 'crc_octets'. I add all files from your project into my project but in file Util crc24Checksum:Data 
![error](https://user-images.githubusercontent.com/24381337/53283304-6dd13900-376a-11e9-8abc-1f683e47dbea.png)

**Comment by agrinman** [comment]
Make sure the PGPFormat.h file is present: https://github.com/kryptco/swift-pgp/blob/master/PGPFormat/PGPFormat.h#L21

**Comment by SPrabhudesai** [comment]
Thanks
